#############################################################################
# Makefile for building: IHMMapEditor
# Generated by qmake (2.01a) (Qt 4.8.4) on: sam. févr. 22 12:31:25 2014
# Project:  IHMMapEditor.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile IHMMapEditor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Iforms -Idisplay -Icore -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		display/mainwindow.cpp \
		display/homewindow.cpp \
		display/editorwindow.cpp \
		display/graphitem.cpp \
		display/mapgraphicsview.cpp \
		xml/parser.cpp \
		core/floor.cpp \
		core/node.cpp \
		core/map.cpp moc_mainwindow.cpp \
		moc_homewindow.cpp \
		moc_editorwindow.cpp \
		moc_graphitem.cpp \
		moc_mapgraphicsview.cpp \
		moc_parser.cpp \
		qrc_iconsResources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		homewindow.o \
		editorwindow.o \
		graphitem.o \
		mapgraphicsview.o \
		parser.o \
		floor.o \
		node.o \
		map.o \
		moc_mainwindow.o \
		moc_homewindow.o \
		moc_editorwindow.o \
		moc_graphitem.o \
		moc_mapgraphicsview.o \
		moc_parser.o \
		qrc_iconsResources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		IHMMapEditor.pro
QMAKE_TARGET  = IHMMapEditor
DESTDIR       = 
TARGET        = IHMMapEditor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_homewindow.h ui_editorwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IHMMapEditor.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile IHMMapEditor.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile IHMMapEditor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/IHMMapEditor1.0.0 || $(MKDIR) .tmp/IHMMapEditor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/IHMMapEditor1.0.0/ && $(COPY_FILE) --parents display/mainwindow.h display/homewindow.h display/editorwindow.h display/graphitem.h display/mapgraphicsview.h xml/parser.h core/floor.h core/node.h core/map.h .tmp/IHMMapEditor1.0.0/ && $(COPY_FILE) --parents iconsResources.qrc .tmp/IHMMapEditor1.0.0/ && $(COPY_FILE) --parents main.cpp display/mainwindow.cpp display/homewindow.cpp display/editorwindow.cpp display/graphitem.cpp display/mapgraphicsview.cpp xml/parser.cpp core/floor.cpp core/node.cpp core/map.cpp .tmp/IHMMapEditor1.0.0/ && $(COPY_FILE) --parents forms/mainwindow.ui forms/homewindow.ui forms/editorwindow.ui .tmp/IHMMapEditor1.0.0/ && (cd `dirname .tmp/IHMMapEditor1.0.0` && $(TAR) IHMMapEditor1.0.0.tar IHMMapEditor1.0.0 && $(COMPRESS) IHMMapEditor1.0.0.tar) && $(MOVE) `dirname .tmp/IHMMapEditor1.0.0`/IHMMapEditor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/IHMMapEditor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_homewindow.cpp moc_editorwindow.cpp moc_graphitem.cpp moc_mapgraphicsview.cpp moc_parser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_homewindow.cpp moc_editorwindow.cpp moc_graphitem.cpp moc_mapgraphicsview.cpp moc_parser.cpp
moc_mainwindow.cpp: display/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) display/mainwindow.h -o moc_mainwindow.cpp

moc_homewindow.cpp: display/homewindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) display/homewindow.h -o moc_homewindow.cpp

moc_editorwindow.cpp: display/editorwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) display/editorwindow.h -o moc_editorwindow.cpp

moc_graphitem.cpp: core/node.h \
		display/graphitem.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) display/graphitem.h -o moc_graphitem.cpp

moc_mapgraphicsview.cpp: display/graphitem.h \
		core/node.h \
		display/mapgraphicsview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) display/mapgraphicsview.h -o moc_mapgraphicsview.cpp

moc_parser.cpp: xml/parser.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) xml/parser.h -o moc_parser.cpp

compiler_rcc_make_all: qrc_iconsResources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_iconsResources.cpp
qrc_iconsResources.cpp: iconsResources.qrc \
		resource/porte.png \
		resource/wc.png \
		resource/issueSecours.png \
		resource/escalier.png \
		resource/qrcode.png \
		resource/ascenseur.png \
		resource/wcH.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name iconsResources iconsResources.qrc -o qrc_iconsResources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_homewindow.h ui_editorwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_homewindow.h ui_editorwindow.h
ui_mainwindow.h: forms/mainwindow.ui \
		display/homewindow.h \
		display/editorwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic forms/mainwindow.ui -o ui_mainwindow.h

ui_homewindow.h: forms/homewindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic forms/homewindow.ui -o ui_homewindow.h

ui_editorwindow.h: forms/editorwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic forms/editorwindow.ui -o ui_editorwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp display/mainwindow.h \
		xml/parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: display/mainwindow.cpp display/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o display/mainwindow.cpp

homewindow.o: display/homewindow.cpp display/homewindow.h \
		ui_homewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o homewindow.o display/homewindow.cpp

editorwindow.o: display/editorwindow.cpp display/editorwindow.h \
		ui_editorwindow.h \
		display/graphitem.h \
		core/node.h \
		display/mapgraphicsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorwindow.o display/editorwindow.cpp

graphitem.o: display/graphitem.cpp display/graphitem.h \
		core/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphitem.o display/graphitem.cpp

mapgraphicsview.o: display/mapgraphicsview.cpp display/mapgraphicsview.h \
		display/graphitem.h \
		core/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapgraphicsview.o display/mapgraphicsview.cpp

parser.o: xml/parser.cpp xml/parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o xml/parser.cpp

floor.o: core/floor.cpp core/floor.h \
		core/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o floor.o core/floor.cpp

node.o: core/node.cpp core/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o core/node.cpp

map.o: core/map.cpp core/map.h \
		core/floor.h \
		core/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o core/map.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_homewindow.o: moc_homewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_homewindow.o moc_homewindow.cpp

moc_editorwindow.o: moc_editorwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorwindow.o moc_editorwindow.cpp

moc_graphitem.o: moc_graphitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphitem.o moc_graphitem.cpp

moc_mapgraphicsview.o: moc_mapgraphicsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapgraphicsview.o moc_mapgraphicsview.cpp

moc_parser.o: moc_parser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parser.o moc_parser.cpp

qrc_iconsResources.o: qrc_iconsResources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_iconsResources.o qrc_iconsResources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

